import {
  Home,
  Users,
  UserCheck,
  Building,
  Menu,
  Settings,
  Shield,
  Database,
  FileText,
  BarChart3,
  Calendar,
  Mail,
  Bell,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  Download,
  Upload,
  Filter,
  RefreshCw,
  ChevronRight,
  ChevronDown,
  MoreHorizontal,
  X,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  Star,
  Heart,
  Bookmark,
  Tag,
  Folder,
  File,
  Image,
  Video,
  Music,
  Archive,
  Clock,
  MapPin,
  Globe,
  Wifi,
  Bluetooth,
  Battery,
  Volume2,
  Camera,
  Mic,
  Phone,
  MessageCircle,
  Share,
  Link,
  ExternalLink,
  Copy,
  Scissors,
  Clipboard,
  Save,
  Printer,
  Zap,
  Target,
  Award,
  Gift,
  ShoppingCart,
  CreditCard,
  DollarSign,
  TrendingUp,
  TrendingDown,
  Activity,
  PieChart,
  BarChart,
  LineChart,
} from 'lucide-react'

// 图标映射表
const iconMap: Record<string, React.ComponentType<any>> = {
  // 基础图标
  home: Home,
  dashboard: Home,
  users: Users,
  user: Users,
  'user-check': UserCheck,
  role: UserCheck,
  roles: UserCheck,
  building: Building,
  organization: Building,
  organizations: Building,
  menu: Menu,
  menus: Menu,
  settings: Settings,
  shield: Shield,
  database: Database,
  'file-text': FileText,
  'bar-chart-3': BarChart3,
  calendar: Calendar,
  mail: Mail,
  bell: Bell,
  search: Search,
  plus: Plus,
  edit: Edit,
  'trash-2': Trash2,
  eye: Eye,
  download: Download,
  upload: Upload,
  filter: Filter,
  'refresh-cw': RefreshCw,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'more-horizontal': MoreHorizontal,
  x: X,
  check: Check,
  'alert-circle': AlertCircle,
  info: Info,
  'help-circle': HelpCircle,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  tag: Tag,
  folder: Folder,
  file: File,
  image: Image,
  video: Video,
  music: Music,
  archive: Archive,
  clock: Clock,
  'map-pin': MapPin,
  globe: Globe,
  wifi: Wifi,
  bluetooth: Bluetooth,
  battery: Battery,
  'volume-2': Volume2,
  camera: Camera,
  mic: Mic,
  phone: Phone,
  'message-circle': MessageCircle,
  share: Share,
  link: Link,
  'external-link': ExternalLink,
  copy: Copy,
  scissors: Scissors,
  clipboard: Clipboard,
  save: Save,
  print: Printer,
  zap: Zap,
  target: Target,
  award: Award,
  gift: Gift,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  activity: Activity,
  'pie-chart': PieChart,
  'bar-chart': BarChart,
  'line-chart': LineChart,
}

// 获取图标组件
export function getMenuIcon(iconName?: string): React.ComponentType<any> {
  if (!iconName) {
    return Menu // 默认图标
  }

  // 转换为小写并替换下划线为连字符
  const normalizedName = iconName.toLowerCase().replace(/_/g, '-')

  return iconMap[normalizedName] || Menu // 如果找不到对应图标，使用默认图标
}

// 导出图标映射表供其他地方使用
export { iconMap }
